USE [master]
GO

/****** Object:  Database [QLCuaHangSach]    Script Date: 11/9/2021 1:56:07 PM ******/
CREATE DATABASE [QLCuaHangSach]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLCuaHangSach', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLCuaHangSach.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLCuaHangSach_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLCuaHangSach_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLCuaHangSach].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLCuaHangSach] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QLCuaHangSach] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLCuaHangSach] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLCuaHangSach] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QLCuaHangSach] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLCuaHangSach] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QLCuaHangSach] SET  MULTI_USER 
GO

ALTER DATABASE [QLCuaHangSach] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLCuaHangSach] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLCuaHangSach] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLCuaHangSach] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLCuaHangSach] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLCuaHangSach] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLCuaHangSach] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLCuaHangSach] SET  READ_WRITE 
GO


